2020-11-05 18:44:43,404 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 18:44:51,726 INFO __main__ VS-bigbase ball_within_template 0 || loading data for generative training...
2020-11-05 19:17:04,954 INFO __main__ VS-bigbase ball_within_template 0 || training 'generative' models...
2020-11-05 19:17:08,527 INFO root training epoch 1...
2020-11-05 19:46:30,488 INFO root collecting auccess after epoch 1...
2020-11-05 19:46:43,843 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 20:04:50,726 INFO root finish collecting auccess after epoch 1: 0.5255207600297446
2020-11-05 20:04:50,727 INFO root training epoch 2...
2020-11-05 20:31:57,155 INFO root collecting auccess after epoch 2...
2020-11-05 20:32:09,557 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 20:48:48,915 INFO root finish collecting auccess after epoch 2: 0.5523900083532663
2020-11-05 20:48:48,916 INFO root training epoch 3...
2020-11-05 21:01:58,315 INFO root training epoch 4...
2020-11-05 21:14:43,065 INFO root training epoch 5...
2020-11-05 21:26:55,487 INFO root collecting auccess after epoch 5...
2020-11-05 21:27:07,543 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 21:43:26,236 INFO root finish collecting auccess after epoch 5: 0.5641865026148891
2020-11-05 21:43:26,237 INFO root training epoch 6...
2020-11-05 21:55:48,484 INFO root training epoch 7...
2020-11-05 22:07:31,294 INFO root training epoch 8...
2020-11-05 22:28:19,415 INFO root training epoch 9...
2020-11-05 22:58:09,628 INFO root training epoch 10...
2020-11-05 23:27:24,727 INFO root collecting auccess after epoch 10...
2020-11-05 23:27:32,468 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-05 23:43:14,725 INFO root finish collecting auccess after epoch 10: 0.5617596866415119
2020-11-05 23:43:14,726 INFO root training epoch 11...
2020-11-06 00:10:42,363 INFO root training epoch 12...
2020-11-06 00:19:39,835 INFO root training epoch 13...
2020-11-06 00:30:03,365 INFO root training epoch 14...
2020-11-06 00:39:14,597 INFO root training epoch 15...
2020-11-06 00:49:55,154 INFO root collecting auccess after epoch 15...
2020-11-06 00:50:00,705 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 00:59:51,817 INFO root finish collecting auccess after epoch 15: 0.5277965139835188
2020-11-06 00:59:51,818 INFO root training epoch 16...
2020-11-06 01:10:15,884 INFO root training epoch 17...
2020-11-06 01:18:59,186 INFO root training epoch 18...
2020-11-06 01:30:00,067 INFO root training epoch 19...
2020-11-06 01:41:29,337 INFO root training epoch 20...
2020-11-06 01:51:27,875 INFO root collecting auccess after epoch 20...
2020-11-06 01:51:33,296 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 02:01:22,430 INFO root finish collecting auccess after epoch 20: 0.5441167469632365
2020-11-06 02:01:22,431 INFO root training epoch 21...
2020-11-06 02:11:44,931 INFO root training epoch 22...
2020-11-06 02:22:19,843 INFO root training epoch 23...
2020-11-06 02:32:11,187 INFO root training epoch 24...
2020-11-06 02:42:24,218 INFO root training epoch 25...
2020-11-06 02:54:43,961 INFO root training epoch 26...
2020-11-06 03:04:45,305 INFO root training epoch 27...
2020-11-06 03:15:18,026 INFO root training epoch 28...
2020-11-06 03:28:06,433 INFO root training epoch 29...
2020-11-06 03:37:18,346 INFO root training epoch 30...
2020-11-06 03:48:33,351 INFO root collecting auccess after epoch 30...
2020-11-06 03:48:38,835 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 03:58:03,537 INFO root finish collecting auccess after epoch 30: 0.5485593920884559
2020-11-06 03:58:39,536 INFO __main__ VS-bigbase ball_within_template 0 || loading data for generative testing...
2020-11-06 03:58:40,105 INFO __main__ VS-bigbase ball_within_template 0 || inspecting generative performance...
2020-11-06 03:58:47,652 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 03:58:52,632 INFO __main__ VS-bigbase ball_cross_template 0 || loading data for generative training...
2020-11-06 03:58:55,963 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 09:33:17,250 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 09:33:25,013 INFO __main__ VS-bigbase ball_within_template 0 -1 || loading models...
2020-11-06 09:33:25,689 INFO __main__ VS-bigbase ball_within_template 0 || getting auccess...
2020-11-06 09:33:38,717 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 09:49:27,456 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 09:49:35,274 INFO __main__ VS-bigbase ball_cross_template 0 -1 || loading models...
2020-11-06 09:49:35,276 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 230, in <module>
    solver.load_models(setup=eval_setup, fold=fold_id, no_second_stage=no_scnd_stage, load_from=load_from)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 2762, in load_models
    self.models[model].load_state_dict(T.load(load_path+f'/{model}.pt', map_location=T.device(device)))
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saves/flownet/VS-bigbase_cross_0_-1/tar_net.pt'
2020-11-06 09:49:41,451 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 09:49:49,165 INFO __main__ VS-bigbase ball_within_template 0 -1 || loading models...
2020-11-06 09:49:49,353 INFO __main__ VS-bigbase ball_within_template 0 || getting auccess...
2020-11-06 09:50:01,872 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 10:05:13,163 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 10:05:21,121 INFO __main__ VS-bigbase ball_cross_template 0 -1 || loading models...
2020-11-06 10:05:21,122 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 230, in <module>
    solver.load_models(setup=eval_setup, fold=fold_id, no_second_stage=no_scnd_stage, load_from=load_from)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 2762, in load_models
    self.models[model].load_state_dict(T.load(load_path+f'/{model}.pt', map_location=T.device(device)))
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saves/flownet/VS-bigbase_cross_0_-1/tar_net.pt'
2020-11-06 10:05:27,447 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 10:05:35,293 INFO __main__ VS-bigbase ball_within_template 0 -1 || loading models...
2020-11-06 10:05:35,447 INFO __main__ VS-bigbase ball_within_template 0 || getting auccess...
2020-11-06 10:05:48,381 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 10:22:43,593 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 10:22:51,393 INFO __main__ VS-bigbase ball_cross_template 0 -1 || loading models...
2020-11-06 10:22:51,397 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 230, in <module>
    solver.load_models(setup=eval_setup, fold=fold_id, no_second_stage=no_scnd_stage, load_from=load_from)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 2762, in load_models
    self.models[model].load_state_dict(T.load(load_path+f'/{model}.pt', map_location=T.device(device)))
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saves/flownet/VS-bigbase_cross_0_-1/tar_net.pt'
